### ISSUE TITLE
 1.19.2 version error reported

### ISSUE THREAD

**Issue by LangKeWAVE** [Luligabi1/NoIndium#10]
I‘m downloaded You provide version. As the title can see it can't run

**Comment by LangKeWAVE** [comment]
curseforge

**Comment by Luligabi1** [comment]
Please provide a error log

**Comment by LangKeWAVE** [comment]
[latest.log](https://github.com/Luligabi1/NoIndium/files/12329969/latest.log)

**Comment by LangKeWAVE** [comment]
00:55:53] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.22
[00:55:53] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[00:55:53] [main/WARN]: Warnings were found!
 - Mod 'Sodium Extra' (sodium-extra) 0.4.16+mc1.19.2-build.90 recommends version 1.4.2 or later of reeses-sodium-options, which is missing!
	 - You should install version 1.4.2 or later of reeses-sodium-options for the optimal experience.

**Comment by LangKeWAVE** [comment]
1.19.2 not have 1.4.2 version Sodium Extra

**Comment by LangKeWAVE** [comment]
[01:12:40] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[01:12:40] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.

**Comment by LangKeWAVE** [comment]
This is my loading mods
reeses_sodium_options-1.6.4+mc1.19.2-build.93
NoIndium-1.1.0+1.19-shadowed
iris-mc1.19.2-1.6.5
dashloader-4.1.3+1.19
lithium-fabric-mc1.19.2-0.11.1
sodium-extra-0.4.16+mc1.19.2-build.90
sodium-fabric-mc1.19.2-0.4.4+build.18
starlight-1.1.1+fabric.ae22326
indium-1.0.9+mc1.19.2

**Comment by Luligabi1** [comment]
> [01:12:40] [Render thread/WARN]: Static binding violation: PRIVATE @overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.

This is not a error on No Indium's side, but Sodium. Also, **you shouldn't install this mod individually; it's meant for mod developers, it won't offer anything for end users.**
