### ISSUE TITLE
[Feature] Add detection for VulkanMod

### ISSUE THREAD

**Issue by moechakucha** [Luligabi1/NoIndium#4]
VulkanMod completely changes Minecraft rendering, so it's probably incompatible with other mods that also do things in rendering (like Sodium).

**Comment by Luligabi1** [comment]
It's the first time I hear about this mod so I'll be cautious as to adding it to indium as that'll require a bit of refactoring for a mod that's on pre-alpha 😅 

> it's probably incompatible with other mods that also do things in rendering (like Sodium).

If that's the case, they should just add sodium to their 'breaks' [dependency resolution list](https://fabricmc.net/wiki/documentation:fabric_mod_json_spec?s[]=breaks).

**Comment by moechakucha** [comment]
> If that's the case, they should just add sodium to their 'breaks' [dependency resolution list](https://fabricmc.net/wiki/documentation:fabric_mod_json_spec?s%5B%5D=breaks).

Unfortunately they [don't](https://github.com/xCollateral/VulkanMod/blob/main/src/main/resources/fabric.mod.json).

**Comment by moechakucha** [comment]
Also it's probably incompatible with any mods that use OpenGL.

**Comment by Luligabi1** [comment]
I'm closing this as I don't think it fits No Indium's scope. NI is meant to act as a failsafe for popular mods that users might add to modpacks and, unbeknownst to them, can cause smaller visual effects malfunctions and occasional crashes, not being so obvious that those mods are the culprits. I sincerly doubt a rendering engine swap wouldn't cause _**A LOT**_ more issues than Sodium or Optifabric could ever do, specially being on pre-alpha.
