### ISSUE TITLE
1.19 update

### ISSUE THREAD

**Issue by Technici4n** [Luligabi1/NoIndium#5]
Hello @Luligabi1, can I request a 1.19 update? The 1.18.2 version seems to be crashing in 1.19.

**Comment by Luligabi1** [comment]
I can try updating it without omega config in a few minutes, with the loss of the modmenu config screen. Would that be ok to you?

**Comment by Technici4n** [comment]
Yeah that's perfectly fine, thanks!

Draylar seems to be MIA for the moment: https://github.com/Draylar/magna/issues/23, so someone else might have to port omega config.

**Comment by Luligabi1** [comment]
> Yeah that's perfectly fine, thanks!

👍🏼 I'll start updating now but I won't be able to finish it until ~~tomorrow~~ **I _really_ underestimated how tired I'd be when I got home. wow.**

> Draylar seems to be MIA for the moment: [Draylar/magna#23](https://github.com/Draylar/magna/issues/23), so someone else might have to port omega config.

[Way ahead of you there ;)](https://github.com/Draylar/omega-config/pull/19)

**Comment by Luligabi1** [comment]
@Technici4n just released the update on CF, Modrinth and Cafeteria's Maven: `1.1.0+1.19`. hmu if you find any issues!

**Comment by Technici4n** [comment]
Thanks
