### ISSUE TITLE
1.19.4 will crash NoIndium

### ISSUE THREAD

**Issue by TelepathicGrunt** [Luligabi1/NoIndium#7]
NoIndium cannot run on 1.19.4 despite being tagged as 1.19.4 on CurseForge for v1.1.0

![image](https://user-images.githubusercontent.com/40846040/229315826-77b8b4ea-784c-4d90-99a3-7819815199d4.png)
 
 Log: https://controlc.com/cd656dc3

**Comment by Luligabi1** [comment]
Sorry for the inconvenience! Uploaded `1.1.0+1.19.4` and untagged `1.1.0+1.19.3` as compatible.
